import{A as b,S as f,N as L,a as k,K as A,b as M}from"./assets/vendor-DcrAUl_J.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const y=document.querySelector(".backdrop"),E=document.querySelector(".open-menu-btn"),C=document.querySelector(".modal-close-btn"),q=document.querySelector(".navi-modal-wrapper"),B=document.querySelector(".modal-order-link"),P=document.querySelector(".navi"),I=document.querySelector(".menu"),F=document.querySelector(".nav-wrapper");E.addEventListener("click",p);C.addEventListener("click",p);q.addEventListener("click",p);B.addEventListener("click",p);I.addEventListener("click",S);F.addEventListener("click",S);function p(){y.classList.toggle("is-open"),document.body.classList.toggle("modal-open");const e=y.classList.contains("is-open");E.setAttribute("aria-expanded",e)}function S(){P.classList.toggle("is-open")}function O(e,s,n){let o=0;const t=document.getElementById(e);t.style.whiteSpace="pre-line";function r(){o<s.length&&(t.textContent+=s.charAt(o),o++,setTimeout(r,n))}r()}O("typed-text",`Hello.
I’m Fullstack developer Lloyd Jefferson.`,50);const T=new b(".accordion-containerX",{duration:400,elementClass:"wrap-item",triggerClass:"icon-wrapper",panelClass:"about-cart"});T.open(0);const h="highlighted-slide";function j(){const e=new f(".about-swiper",{modules:[L],spaceBetween:0,loop:!0,centeredSlides:!1,touchRatio:1,initialSlide:0,grabCursor:!0,keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".about-swip-arrow-next",prevEl:".about-swip-arrow-prev"},breakpoints:{0:{slidesPerView:2},768:{slidesPerView:"auto"}},on:{init:function(){m(this)},slideChange:function(){m(this)},resize:function(){m(this)}}});document.addEventListener("keydown",function(s){s.key==="ArrowRight"?e.slideNext():s.key==="ArrowLeft"&&e.slidePrev()})}function m(e){const s=e.slides;s.forEach(t=>t.classList.remove(h));const n=e.realIndex,o=Array.from(s).find(t=>Number(t.dataset.swiperSlideIndex)===n&&!t.classList.contains("swiper-slide-duplicate"));o&&o.classList.add(h)}document.addEventListener("DOMContentLoaded",j);const a=new f(".projects-swiper",{slidesPerView:1,spaceBetween:20,keyboard:{enabled:!0,onlyInViewport:!0},a11y:!0}),u=document.querySelector(".icon-wrapper.left"),v=document.querySelector(".icon-wrapper.right");u.addEventListener("click",()=>{u.classList.contains("disabled")||a.slidePrev()});v.addEventListener("click",()=>{v.classList.contains("disabled")||a.slideNext()});a.on("slideChange",()=>{u.classList.toggle("disabled",a.isBeginning),v.classList.toggle("disabled",a.isEnd)});window.addEventListener("DOMContentLoaded",()=>{u.classList.add("disabled"),document.addEventListener("keydown",e=>{e.key==="ArrowLeft"?a.slidePrev():e.key==="ArrowRight"&&a.slideNext()})});new b(".accordion-container");const d=document.querySelector("#covers");document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".covers-list-wrapper").forEach(s=>{const n=s.querySelector(".covers-list"),o=Array.from(n.children);if(o.length>0){const t=o[o.length-1].outerHTML,r=o.slice(0,o.length-1).map(c=>c.outerHTML).join("");n.innerHTML+=t+r}})});if(d){const e={root:null,rootMargin:"0px",threshold:.1};new IntersectionObserver(n=>{n.forEach(o=>{o.isIntersecting?d.classList.add("animate"):d.classList.remove("animate")})},e).observe(d)}else console.error('Element with id "covers" not found in the DOM.');const V="https://portfolio-js.b.goit.study/api/reviews";async function N(){try{return(await k.get(V)).data}catch(e){throw console.error("Error fetching reviews:",e),new Error("Failed to fetch reviews")}}async function H(){const e=document.getElementById("reviews-list");if(e)try{const s=await N();e.innerHTML=s.map(n=>`<li class="reviews-swiper-slide swiper-slide">
          <div class="review-card">
            <img
              class="review-avatar"
              src="${n.avatar_url}"
              alt="${n.author}"
            />
            <h3 class="avatar-name">${n.author}</h3>
            <p class="review-item">
              ${n.review}
            </p>
          </div>
        </li>`).join(""),R()}catch{e.innerHTML='<p class="error-message">Not found</p>'}}H();function R(){new f(".reviews-swiper",{modules:[L,A],slidesPerView:"auto",navigation:{nextEl:".swiper-button-next-1",prevEl:".swiper-button-prev-1"},keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2,grabCursor:!0,spaceBetween:16},1440:{slidesPerView:4,grabCursor:!0,spaceBetween:16}},on:{slideChange:function(){const e=document.querySelector(".swiper-button-prev-1"),s=document.querySelector(".swiper-button-next-1");e.disabled=this.isBeginning,s.disabled=this.isEnd,this.isBeginning?e.classList.add("disabled"):e.classList.remove("disabled"),this.isEnd?s.classList.add("disabled"):s.classList.remove("disabled")}}})}let w=!1;const x=document.querySelector(".work-form"),l=document.querySelector(".work-input"),i=document.querySelector(".js-input-message");l.addEventListener("input",D);function D(){l.value.trim()?l.checkValidity()?(i.textContent="Succes!",i.classList.remove("error"),i.classList.add("success"),i.style.visibility="visible",l.style.borderBottom="1px solid #3cbc81"):(i.textContent="Invalid email, try again",i.classList.remove("success"),i.classList.add("error"),i.style.visibility="visible",l.style.borderBottom="1px solid #e74a3b"):(i.style.visibility="hidden",l.style.borderBottom="1px solid rgba(250, 250, 250, 0.2)")}x.addEventListener("submit",$);function $(e){if(e.preventDefault(),w)return;const s=document.querySelector('input[type="email"]').value.trim(),n=document.querySelector('input[type="text"]').value.trim(),o={email:s,comment:n},t="https://portfolio-js.b.goit.study/api-docs/reqests";w=!0,k.post(t,o,{headers:{"Content-Type":"application/json"}}).then(r=>{x.reset(),i.style.visibility="hidden",l.style.borderBottom="1px solid rgba(250, 250, 250, 0.2)",g("success")}).catch(r=>{g("error")}).finally(()=>{w=!1})}function g(e){const s=K(e),n=M.create(s,{onShow:c=>{document.addEventListener("keydown",r)},onClose:c=>{document.removeEventListener("keydown",r)}});n.show(),document.body.style.overflow="hidden";const o=n.element().querySelector(".work-close-btn");o.addEventListener("click",t);function t(){n.close(),document.body.style.overflow="",o.removeEventListener("click",t)}function r(c){c.key==="Escape"&&(document.activeElement.blur(),n.close(),document.body.style.overflow="",o.removeEventListener("click",t))}}function K(e){if(e==="success")return`
      <div class="work-modal-sucssec">
        <button type="button" class="work-close-btn">
        <svg  class="work-icon" width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M16.5 5.5L5.5 16.5" stroke="#FAFAFA" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M5.5 5.5L16.5 16.5" stroke="#FAFAFA" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg> 
        </button>
        <h3 class="work-modal-title">Thank you for your interest in cooperation!</h3>
        <p class="work-modal-text">The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.</p>
      </div>
    `;if(e==="error")return`
      <div class="work-modal-sucssec">
        <button type="button" class="work-close-btn">
            <svg  class="work-icon" width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M16.5 5.5L5.5 16.5" stroke="#FAFAFA" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M5.5 5.5L16.5 16.5" stroke="#FAFAFA" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
        </button>
        <h3 class="work-modal-title"><span class="work-modal-span-erorr">Oops!</span> Something went wrong.</h3>
        <p class="work-modal-text">Please try again later.</p>
      </div>
    `}
//# sourceMappingURL=index.js.map
