import{A as L,S as w,N as k,a as E,K as C,b as q}from"./assets/vendor-C2sjyuOS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function s(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(o){if(o.ep)return;o.ep=!0;const n=s(o);fetch(o.href,n)}})();const f=document.querySelector(".backdrop"),S=document.querySelector(".open-menu-btn"),B=document.querySelector(".modal-close-btn"),M=document.querySelector(".navi-modal-wrapper"),F=document.querySelector(".navi"),P=document.querySelector(".menu"),O=document.querySelector(".nav-wrapper");S.addEventListener("click",v);B.addEventListener("click",v);M.addEventListener("click",v);P.addEventListener("click",x);O.addEventListener("click",x);function v(){f.classList.toggle("is-open"),document.body.classList.toggle("modal-open");const e=f.classList.contains("is-open");S.setAttribute("aria-expanded",e)}function x(){F.classList.toggle("is-open")}function I(e,t,s){let r=0;const o=document.getElementById(e);o.style.whiteSpace="pre-line";function n(){r<t.length&&(o.textContent+=t.charAt(r),r++,setTimeout(n,s))}n()}I("typed-text",`Hello.
I’m Fullstack developer Lloyd Jefferson.`,50);const j=new L(".accordion-containerX",{duration:400,elementClass:"wrap-item",triggerClass:"icon-wrapper",panelClass:"about-cart"});j.open(0);function V(){new w(".about-swiper",{modules:[k],slidesPerView:"auto",spaceBetween:20,loop:!0,keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".about-swip-arrow-next",prevEl:".about-swip-arrow-prev"},grabCursor:!0,on:{init:function(){b()},loopFix:function(){b()}}})}const y="highlighted-slide";function b(){document.querySelectorAll(".about-swiper .swiper-slide").forEach(t=>{t.removeEventListener("click",h),t.addEventListener("click",h)})}function h(e){const t=e.currentTarget;document.querySelectorAll(".about-swiper .swiper-slide").forEach(s=>{s.classList.remove(y)}),t.classList.add(y)}document.addEventListener("DOMContentLoaded",V);const a=new w(".projects-swiper",{slidesPerView:1,spaceBetween:20,keyboard:{enabled:!0,onlyInViewport:!0},a11y:!0}),d=document.querySelector(".icon-wrapper.left"),p=document.querySelector(".icon-wrapper.right");d.addEventListener("click",()=>{d.classList.contains("disabled")||a.slidePrev()});p.addEventListener("click",()=>{p.classList.contains("disabled")||a.slideNext()});a.on("slideChange",()=>{a.isBeginning?d.classList.add("disabled"):d.classList.remove("disabled"),a.isEnd?p.classList.add("disabled"):p.classList.remove("disabled")});window.addEventListener("DOMContentLoaded",()=>{d.classList.add("disabled")});new L(".accordion-container");document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".covers-list-wrapper").forEach(t=>{const s=t.querySelector(".covers-list");if(s){const r=s.cloneNode(!0);r.classList.add("duplicate"),t.appendChild(r)}})});const u=document.querySelector("#covers");if(u){const e={root:null,rootMargin:"0px",threshold:.1};new IntersectionObserver(s=>{s.forEach(r=>{r.isIntersecting?(console.log("Section is in view"),u.classList.add("animate")):(console.log("Section is out of view"),u.classList.remove("animate"))})},e).observe(u)}else console.error('Element with id "covers" not found in the DOM.');const T="https://portfolio-js.b.goit.study/api/reviews";async function N(){try{return(await E.get(T)).data}catch(e){throw console.error("Error fetching reviews:",e),new Error("Failed to fetch reviews")}}async function D(){const e=document.getElementById("reviews-list");if(e)try{const t=await N();e.innerHTML=t.map(s=>`<li class="reviews-swiper-slide swiper-slide">
          <div class="review-card">
            <img
              class="review-avatar"
              src="${s.avatar_url}"
              alt="${s.author}"
            />
            <h3 class="avatar-name">${s.author}</h3>
            <p class="review-item">
              ${s.review}
            </p>
          </div>
        </li>`).join(""),H()}catch{e.innerHTML='<p class="error-message">Not found</p>'}}D();function H(){new w(".reviews-swiper",{modules:[k,C],slidesPerView:"auto",navigation:{nextEl:".swiper-button-next-1",prevEl:".swiper-button-prev-1"},keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2,grabCursor:!0,spaceBetween:16},1440:{slidesPerView:4,grabCursor:!0,spaceBetween:16}},on:{slideChange:function(){const e=document.querySelector(".swiper-button-prev-1"),t=document.querySelector(".swiper-button-next-1");e.disabled=this.isBeginning,t.disabled=this.isEnd,this.isBeginning?e.classList.add("disabled"):e.classList.remove("disabled"),this.isEnd?t.classList.add("disabled"):t.classList.remove("disabled")}}})}let m=!1;const A=document.querySelector(".work-form"),c=document.querySelector(".work-input"),i=document.querySelector(".js-input-message");c.addEventListener("input",R);function R(){c.value.trim()?c.checkValidity()?(i.textContent="Succes!",i.classList.remove("error"),i.classList.add("success"),i.style.visibility="visible",c.style.borderBottom="1px solid #3cbc81"):(i.textContent="Invalid email, try again",i.classList.remove("success"),i.classList.add("error"),i.style.visibility="visible",c.style.borderBottom="1px solid #e74a3b"):(i.style.visibility="hidden",c.style.borderBottom="1px solid rgba(250, 250, 250, 0.2)")}A.addEventListener("submit",$);function $(e){if(e.preventDefault(),m)return;const t=document.querySelector('input[type="email"]').value.trim(),s=document.querySelector('input[type="text"]').value.trim(),r={email:t,comment:s},o="https://portfolio-js.b.goit.study/api-docs/reqests";m=!0,E.post(o,r,{headers:{"Content-Type":"application/json"}}).then(n=>{A.reset(),i.style.visibility="hidden",c.style.borderBottom="1px solid rgba(250, 250, 250, 0.2)",g("success")}).catch(n=>{g("error")}).finally(()=>{m=!1})}function g(e){const t=K(e),s=q.create(t);s.show(),document.body.style.overflow="hidden";const r=s.element().querySelector(".work-close-btn");r.addEventListener("click",o);function o(){s.close(),document.body.style.overflow="",r.removeEventListener("click",o),document.removeEventListener("keydown",n)}document.addEventListener("keydown",n);function n(l){l.key==="Escape"&&(document.activeElement.blur(),s.close(),document.body.style.overflow="",r.removeEventListener("click",o),document.removeEventListener("keydown",n))}}function K(e){if(e==="success")return`
      <div class="work-modal-sucssec">
        <button type="button" class="work-close-btn">
        <svg  class="work-icon" width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M16.5 5.5L5.5 16.5" stroke="#FAFAFA" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M5.5 5.5L16.5 16.5" stroke="#FAFAFA" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg> 
        </button>
        <h3 class="work-modal-title">Thank you for your interest in cooperation!</h3>
        <p class="work-modal-text">The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.</p>
      </div>
    `;if(e==="error")return`
      <div class="work-modal-sucssec">
        <button type="button" class="work-close-btn">
            <svg  class="work-icon" width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M16.5 5.5L5.5 16.5" stroke="#FAFAFA" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M5.5 5.5L16.5 16.5" stroke="#FAFAFA" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
        </button>
        <h3 class="work-modal-title"><span class="work-modal-span-erorr">Oops!</span> Something went wrong.</h3>
        <p class="work-modal-text">Please try again later.</p>
      </div>
    `}
//# sourceMappingURL=index.js.map
